# .gitlab-ci.yml

# Define the stages: build -> deploy
stages:
  - build
  - deploy

# Cache node_modules for faster builds
cache:
  paths:
    - node_modules/

# Define the image to be used for CI
image: node:20

# Set environment variables during the build stage:
variables:
  VITE_BASE_URL: ''

# Build stage to install dependencies and build the static site
build:
  stage: build
  script:
    - bun install # Install dependencies
    - bun run build # Ensure running the build script inside 'react' workspace
  artifacts:
    paths:
      - '/dist/' # Ensure this directory is where Vite outputs the build artifacts

# Deploy to GitLab Pages in the /public directory
pages:
  stage: deploy
  script:
    - mv dist public/
  artifacts:
    paths:
      - public/ # GitLab Pages will serve content from the 'public' directory