# .gitlab-ci.yml

# Define the stages: build -> deploy
stages:
  - build
  - deploy

# Cache node_modules for faster builds
cache:
  paths:
    - 'node_modules/'
    - 'bun.lockb'

# Define the image to be used for CI
image: node:20

# Set environment variables during the build stage:
variables:
  VITE_BASE_URL: 'https://sensornode.shop'

# Build stage to install dependencies and build the static site
build:
  stage: build
  script:
    - curl -fsSL https://bun.sh/install | bash
    - export BUN_INSTALL="$HOME/.bun"
    - export PATH="$BUN_INSTALL/bin:$PATH"
    - bun install
    - bun run build
    - ls -l dist/
  artifacts:
    paths:
      - 'dist/'

# Deploy to GitLab Pages in the /public directory
pages:
  image: node:20
  stage: deploy
  script:
    - cp -r dist/* public/
    - mv dist public/
  artifacts:
    paths:
      - public # GitLab Pages will serve content from the 'public' directory
  only:
    - master